"""Clip Check data for Lori Vallow Episode 1 (final v7). No em dashes anywhere in this file."""

TOTAL = 155.0
VIDEO = "LoriVallow_EP01_The_Man_Who_Was_Afraid_v7_captions_1080p.mp4"

# source group, owner, how obtained, what is on screen, use class, type, verdict, fix, issues
CLS = {
    "charles_portrait.jpg": ("Victim and family photos", "Unknown (image supplied by the producer)", "Supplied by the producer; capture method not recorded",
        "Portrait of Charles Vallow, arms crossed", "Carrying (the subject shown as a picture)", "V15", "DON'T",
        "Written family consent and the original owner are both missing. Replace with a title card or own graphic, or get consent in writing.", "C"),
    "chandler_aerial.jpg": ("Creative Commons images", "Chris J (Wikimedia Commons), CC BY-SA 2.0", "Downloaded by the producer from the Commons file page; licence listed in _CREDITS.csv",
        "Aerial view of Chandler, Arizona", "Mood / establishing", "V14", "USE IF",
        "Add on-screen credit 'Chris J, CC BY-SA 2.0, edited by Osira' and in the end card. Save a dated licence page. Counsel: share-alike on our cropped, graded version.", "E"),
    "photo_wedding.jpg": ("Victim and family photos", "Unknown (taken from the earlier draft video)", "Frame grab from the producer's draft video; original not traced",
        "Wedding photo of Charles and Lori Vallow", "Carrying", "V15", "DON'T",
        "Charles is a homicide victim and the owner is unknown. Replace, or get written family consent and the original file.", "C"),
    "photo_charles_baby.jpg": ("Victim and family photos", "Unknown (taken from the earlier draft video)", "Frame grab from the producer's draft video; original not traced",
        "Charles holding a baby (baby's face blurred by us)", "Carrying", "V15", "DON'T",
        "Victim photo without consent, and it shows a minor. Replace with a text card or own graphic.", "C"),
    "real_night_a.mp4": ("Police bodycam (Jan 31, 2019)", "Gilbert Police Department (agency release); our file is a Law&Crime copy", "Supplied by the producer in a bodycam reference zip; the file carries a Law&Crime logo; capture method not recorded",
        "Man in a cap, night street, hand movements; burnt-in time stamp 2019-01-31", "Mood (no statement is audible or shown)", "V05 / V10", "DON'T",
        "Our file is the Law&Crime copy and the logo was cropped out. Re-take from Gilbert PD's own release, fix the tag to Gilbert PD, or drop.", "B"),
    "real_lori_car.mp4": ("Police-style clips, source unidentified", "Unidentified", "Supplied by the producer inside the draft video; original not traced",
        "Woman with sunglasses leaning on a red car", "Carrying", "V10 (unverified)", "NOT CLEARED",
        "Tag says 'Bodycam, Arizona Police 2019' but we never confirmed this is police footage or which agency. Trace the original or cut.", "F"),
    "real_int_1.mp4": ("Police interview video (Jul 11, 2019)", "Chandler Police Department (burnt-in text); copy origin unknown", "Supplied by the producer; capture method not recorded",
        "Interview room, Lori Vallow seated, wide shot on a card", "Subject (her own statements)", "V10", "USE IF",
        "Confirm the file is the agency's own release (not an outlet copy). Keep agency and date tag.", "F"),
    "lori_booking.jpg": ("Booking photos (agency, via copies)", "Kauai Police Department (per file name); copy origin unknown", "Supplied by the producer (image file); capture method not recorded",
        "Lori Vallow booking photo on a print", "Subject (who she is)", "V10 (booking photo)", "USE IF",
        "Trace to the agency release or its court file. Keep agency and year tag. Counsel: booking photos for a German audience.", "F"),
    "doc_p04.jpg": ("Court record pages", "Maricopa County Superior Court, case FC2019-092936", "Supplied by the producer as page images; capture method not recorded",
        "Divorce petition page with red pencil highlights (text read aloud)", "Subject (the record we quote)", "V13 (court record)", "USE IF",
        "Take the pages from the court's own file, remove the stray file name '004.jpg' visible at the top, credit the court record.", "F"),
    "ai_world.jpg": ("Own AI and graphics", "Osira (Nano Banana 2 image)", "Generated on Magnific via its connector", "Earth from orbit with faint fire glow",
        "Own AI (symbolic)", "V18", "USE IF", "Replace the small ILLUSTRATION tag with a readable KI-GENERIERT / AI-GENERATED label.", "D"),
    "ai_calendar.mp4": ("Own AI and graphics", "Osira (Nano Banana 2 image, Kling 3.0 video)", "Generated on Magnific via its connector", "Wall calendar JULY 2020 with a circled date",
        "Own AI (symbolic)", "V18", "USE IF", "Readable AI label. Remove the circled 24: no source says that date.", "D, H"),
    "doc_p03.jpg": ("Court record pages", "Maricopa County Superior Court, case FC2019-092936", "Supplied by the producer as page images; capture method not recorded",
        "Divorce petition page with one highlighted line", "Subject (the record we quote)", "V13 (court record)", "USE IF",
        "Same as the other filing pages: court's own file, no stray file name, credit.", "F"),
    "real_int_2.mp4": ("Police interview video (Jul 11, 2019)", "Chandler Police Department (burnt-in text); copy origin unknown", "Supplied by the producer; capture method not recorded",
        "Lori Vallow in the interview room, vertical crop", "Subject (her own statements)", "V10", "USE IF",
        "Same as the other interview shots: confirm it is the agency's release.", "F"),
    "real_night_c.mp4": ("Police bodycam (Jan 31, 2019)", "Gilbert Police Department (agency release); our file is a Law&Crime copy", "Supplied by the producer in a bodycam reference zip; Law&Crime logo present",
        "Man in a cap reaching up at a door at night", "Mood", "V05 / V10", "DON'T",
        "See issue B.", "B"),
    "real_charles_cap.mp4": ("Police-style clips, source unidentified", "Unidentified", "Supplied by the producer inside the draft video (a screen recording; cursor visible in the source)",
        "Man in a cap gesturing in a garage with bicycles", "Mood", "V10 (unverified)", "NOT CLEARED",
        "Tagged 'Bodycam, Chandler Police 2019' without proof. Identify the original or cut.", "F"),
    "real_to_door.mp4": ("Police bodycam (Jan 31, 2019)", "Gilbert Police Department (agency release); our file is a Law&Crime copy", "Supplied by the producer in a bodycam reference zip; Law&Crime logo present",
        "Dark figure walking past a doorway", "Mood", "V05 / V10", "DON'T", "See issue B.", "B"),
    "photo_charles.jpg": ("Victim and family photos", "Unknown (taken from the earlier draft video)", "Frame grab from the producer's draft video; original not traced",
        "Close photo of Charles Vallow", "Carrying", "V15", "DON'T",
        "Victim photo, owner unknown. Replace or get written family consent.", "C"),
    "chad_booking.jpg": ("Booking photos (agency, via copies)", "Fremont County, Idaho (per our label); the file came from a TV-style graphic", "Supplied by the producer (image file with a news graphic around it); we cropped the graphic out",
        "Chad Daybell booking photo on a print", "Subject (who he is)", "V10 (booking photo)", "NOT CLEARED",
        "The copy is an outlet graphic, so trace the agency's own release. Keep the agency and year tag only once confirmed.", "F"),
    "ai_writer_desk.jpg": ("Own AI and graphics", "Osira (Nano Banana 2 image)", "Generated on Magnific via its connector", "Empty writing desk at night, books and notes, no person",
        "Own AI (symbolic)", "V18", "USE IF", "Readable AI label.", "D"),
    "real_int_3.mp4": ("Police interview video (Jul 11, 2019)", "Chandler Police Department (burnt-in text); copy origin unknown", "Supplied by the producer; capture method not recorded",
        "Interview room wide card with a slow zoom", "Subject (her own statements)", "V10", "USE IF", "Same as the other interview shots.", "F"),
    "ai_watching.mp4": ("Own AI and graphics", "Osira (Nano Banana 2 image, Kling 2.5 video)", "Generated on Magnific via its connector", "Man seen from behind watching a woman in a dining room",
        "Own AI (reenactment)", "V18", "USE IF", "Readable AI label. Both people stay faceless; keep it that way.", "D"),
    "real_bodycam_walk.mp4": ("Police bodycam (Jan 31, 2019)", "Gilbert Police Department (agency release); our file is a Law&Crime copy", "Supplied by the producer in a bodycam reference zip; Law&Crime logo present",
        "Night street with a lit house", "Mood", "V05 / V10", "DON'T", "See issue B.", "B"),
    "ai_family_court.mp4": ("Own AI and graphics", "Osira (Nano Banana 2 image, Kling 3.0 video)", "Generated on Magnific via its connector", "Man seen from behind at a court clerk's counter with a folder",
        "Own AI (reenactment)", "V18", "USE IF", "Readable AI label.", "D"),
    "doc_p01.jpg": ("Court record pages", "Maricopa County Superior Court, case FC2019-092936", "Supplied by the producer as page images; capture method not recorded",
        "First page of the petition: law firm block and the parties", "Subject (the record we quote)", "V13 (court record)", "USE IF",
        "Blur the minor child's name in the case text. The law firm's street address and email are on this page; keep only if needed.", "F, G"),
    "ai_i_will.jpg": ("Own AI and graphics", "Osira (draft AI frame, from the producer's earlier draft)", "Frame from the producer's draft video", "Hand writing 'I will' on paper",
        "Own AI (reenactment)", "V18", "USE IF",
        "Readable AI label. The on-screen words continue the quote in issue A, which is not in the record.", "A, D"),
    "real_gate.mp4": ("Police bodycam (Jan 31, 2019)", "Gilbert Police Department (agency release); our file is a Law&Crime copy", "Supplied by the producer in a bodycam reference zip; Law&Crime logo present",
        "Flashlight beam and a gate", "Mood", "V05 / V10", "DON'T", "See issue B.", "B"),
    "real_night_b.mp4": ("Police bodycam (Jan 31, 2019)", "Gilbert Police Department (agency release); our file is a Law&Crime copy", "Supplied by the producer in a bodycam reference zip; Law&Crime logo present",
        "Man in a cap looking up at night", "Mood", "V05 / V10", "DON'T", "See issue B.", "B"),
    "real_court.mp4": ("Creative Commons images", "Tony Webster (Wikimedia Commons), CC BY 2.0", "Downloaded by the producer from the Commons file page; licence listed in _CREDITS.csv",
        "Maricopa County Superior Court sign on a card", "Mood / location", "V14", "USE IF",
        "Add on-screen credit 'Tony Webster, CC BY 2.0, edited by Osira' and in the end card. Save a dated licence page.", "E"),
    "real_charles_day.mp4": ("Police bodycam (Jan 31, 2019)", "Gilbert Police Department (agency release); our copy came from the draft video", "Frame grab from the producer's draft video; original not traced",
        "Charles Vallow in a cap, daylight, burnt-in 2019-01-31 stamp", "Carrying", "V10 (unverified copy)", "NOT CLEARED",
        "Same release as issue B (the time stamp says Jan 31, 2019). Trace the original and fix the tag to the right agency.", "B, F"),
    "real_charles_close.mp4": ("Police bodycam (Jan 31, 2019)", "Gilbert Police Department (agency release); our file is a Law&Crime copy", "Supplied by the producer in a bodycam reference zip; Law&Crime logo present",
        "Large man walking in with officers in a lit garage", "Mood", "V05 / V10", "DON'T", "See issue B.", "B"),
    "real_walkaway.mp4": ("Police bodycam (Jan 31, 2019)", "Gilbert Police Department (agency release); our file is a Law&Crime copy", "Supplied by the producer in a bodycam reference zip; Law&Crime logo present",
        "Figures walking off down a street", "Mood", "V05 / V10", "DON'T", "See issue B.", "B"),
    "ai_party.mp4": ("Own AI and graphics", "Osira (Nano Banana 2 image, Kling 2.5 video)", "Generated on Magnific via its connector", "Man seen from behind telling a story at a backyard party",
        "Own AI (reenactment)", "V18", "USE IF", "Readable AI label.", "D"),
    "ai_family_hug.mp4": ("Own AI and graphics", "Osira (Nano Banana 2 image, Kling 2.5 video)", "Generated on Magnific via its connector", "Family of four hugging on a porch at sunset, all from behind",
        "Own AI (reenactment)", "V18", "USE IF", "Readable AI label. Shows two children as AI stand-ins for real children (issue D).", "D"),
    "ai_garden_kids.mp4": ("Own AI and graphics", "Osira (the producer's own AI clip)", "Supplied by the producer (AI generated shots folder)", "Teen girl and small boy seen from behind in a garden",
        "Own AI (reenactment)", "V18", "USE IF", "Readable AI label. Shows two children as AI stand-ins for real children (issue D).", "D"),
    "ai_boy_floor.mp4": ("Own AI and graphics", "Osira (the producer's own AI clip)", "Supplied by the producer (AI generated shots folder)", "Small boy seen from behind playing on a floor",
        "Own AI (reenactment)", "V18", "USE IF", "Readable AI label. Stands in for a real child (issue D).", "D"),
    "ai_family_tv.jpg": ("Own AI and graphics", "Osira (the producer's own AI image)", "Supplied by the producer (AI generated shots folder); TV screen blurred by us", "Family of four seen from behind watching TV",
        "Own AI (reenactment)", "V18", "USE IF", "Readable AI label. Shows children as AI stand-ins (issue D).", "D"),
}

END_CARD = ("end card", 150.4, 4.6)

ISSUES = [
    ("A", "122.6 to 132.0 (quote cards at 126.3 to 132.0; AI hand at 122.6)", "Quoted words are not in the record",
     "Narration and captions give 'I will kill you, because you're not Charles, and nobody will care' as the exact words Lori said, written in the court papers. We read all 19 filing pages (OCR): those words appear on none of them. Page 4 says only that she 'would kill him upon his return home'. A summary of the police report on Court TV quotes different words ('You're not Charles. I don't know who you are or what you did with Charles, but I can murder you now with my powers'). We could not open that page (blocked), so that wording is also UNVERIFIED.",
     "A misquote tied to a named person, with quotation marks and 'exact words'. This is a red line (invented or misquoted words).",
     "Red", "Use only the petition's own words in quote marks ('she would kill him upon his return home', page 4), or paraphrase with no quote marks. The voiceover also says the line, so the producer must re-record or soften that sentence. Verify any other wording against the original at its timestamp."),
    ("B", "11 shots: 31.95, 77.3, 84.2, 112.3, 132.0, 134.2, 143.1, 145.8 (bodycam); 36.6, 80.9, 140.9 (unidentified or unverified)", "Bodycam copy with the logo removed, and the wrong agency on screen",
     "Our bodycam file shows a Law&Crime logo (bottom left of the original). We cropped the frame so the logo is out of the picture, then zoomed in. KUTV (opened) states Gilbert Police released this footage; our tags say Chandler Police on every shot. The producer's own README says these clips are 'rough-cut use only, not cleared for broadcast'. Seven of the eight bodycam shots show no statement at all, only mood.",
     "Law&Crime is on the never list; stripped logos are a red line; a wrong source tag is a false record on screen; mood footage fails test 1.",
     "Red", "Re-take the one clip that carries Charles's statement from Gilbert PD's own release (public records) the approved way, tag it Gilbert Police Department with the exact date. Replace the rest with own graphics, AI or court record. Never crop a logo out."),
    ("C", "0.0, 14.9, 25.1, 87.3", "Photos of Charles Vallow (a homicide victim), no consent, unknown owners",
     "Four photos of Charles: the opening portrait, the wedding photo, the photo holding a baby, and a close portrait. None has a traced owner. The baby photo also shows a minor (face blurred by us). Charles was killed on 11 July 2019 (KSL, opened).",
     "Victims' photos need written family consent (V15). German post-mortem image rights run 10 years after death, so until 2029 (s. 22 KUG).",
     "Red", "Get written consent and the original file for each, or replace with a title card, a text card ('Charles Vallow, 62') or the court record."),
    ("D", "All AI shots (s03 to s10, s16, s17, s25b, s27, s29, s31)", "AI labels too small and not the required wording; children shown as AI stand-ins",
     "Labels read REENACTMENT or ILLUSTRATION at about 19 px, top right. The rule asks for a readable KI-GENERIERT / AI-GENERATED. The AI shots are photoreal and stand in for real people, including children (Tylee and J.J.) in four shots.",
     "EU AI Act Art. 50(4) disclosure; the guide says no single private person or child shown.",
     "Fix", "Replace every label with 'KI-GENERIERT / AI-GENERATED', larger and on screen for the whole shot. Counsel or producer to decide whether AI children from behind are acceptable."),
    ("E", "4.55 and 136.4", "Creative Commons credits missing; share-alike",
     "The Chandler aerial is CC BY-SA 2.0 (Chris J). The court sign is CC BY 2.0 (Tony Webster). Neither is credited on screen or in an end card. The aerial was cropped and graded, and BY-SA requires an edited version to be shared under the same licence.",
     "CC BY needs credit in the required format; CC BY 4.0 s. 2(a)(5)(B) leaves the DRM question open for counsel.",
     "Fix", "Add credits in the form 'Owner, licence, edited by Osira' on screen and in the end card; save a dated licence page per image; send the share-alike and DRM points to counsel."),
    ("F", "36.6, 80.9, 94.9, 44.7, 40.9, 73.4, 102.6, 48.9 to 132.0 (filing pages)", "Sources not traced or not verified",
     "The Lori car clip is tagged 'Arizona Police 2019' and the garage clip 'Chandler Police 2019' with no proof. The Chad Daybell photo came inside a TV-style graphic. Both booking photos came as image files with no agency release. The interview video is an unconfirmed copy. The filing page images have a stray file name ('004.jpg') visible at the top on screen.",
     "The agency, owner and method for these files are unknown; on-screen tags might be false.",
     "Fix", "Trace each to the owner's own release, correct or drop the tags, and remove the stray file name. Log how each file was obtained, truthfully."),
    ("G", "119.5 to 122.6", "Minor's name visible in the filing",
     "Page 1 of the petition shows the child's name in the case text. The law firm's street address and email are also readable on the same page.",
     "Minors should not be identifiable; the address and email are public record but not needed.",
     "Edge", "Blur the minor's name; consider blurring the address and email."),
    ("H", "64.9 to 67.8", "Calendar shows a circled date no source gives",
     "The AI calendar (JULY 2020) has the 24th circled. The narration says only 'the summer of 2020'.",
     "A made-up detail presented as part of the story.", "Edge", "Remove the circle or use a neutral calendar."),
]

COUNSEL = [
    "CC BY-SA 2.0 (Chandler aerial): do the share-alike terms bind our cropped, colour-graded version when shown inside a paid app?",
    "CC BY 4.0 s. 2(a)(5)(B) and DRM: any CC licensed image or clip inside a DRM-protected app, until you confirm this point is safe (applies to the court sign and the aerial).",
    "Charles Vallow's photos: who can give consent (family, estate), and does s. 22 KUG (10 years after death, to July 2029) apply to the baby photo and the portraits?",
    "AI stand-ins for real children from behind (Tylee, J.J.): acceptable, or blur or remove?",
    "Booking photos of convicted people for a German audience: any restriction beyond the agency source?",
    "Bodycam: if Gilbert PD's own release is public, does a Law&Crime copy change anything, and what exact credit line is required?",
    "A minor's name inside a court record shown on screen: blur or acceptable?",
]

SOURCES = [
    ("KUTV, 'BODY CAM: Charles Vallow tells police his wife Lori Vallow wants him dead'", "https://kutv.com/news/nation-world/body-cam-charles-vallow-tells-police-his-wife-lori-vallow-wants-him-dead", "Opened. Says the footage was released by Gilbert Police Department through public records."),
    ("KSL, 'Who is Charles Vallow?'", "https://www.ksl.com/article/news/utah/police-and-courts/who-is-charles-vallow/51567401", "Opened. Charles died 11 July 2019 at age 62."),
    ("CBS News, Arizona verdict", "https://www.cbsnews.com/news/lori-vallow-daybell-verdict-arizona-trial/", "Opened. Convicted 22 April 2025 of conspiring to murder Charles Vallow."),
    ("KSL, 'Chad Daybell sentenced to death'", "https://www.ksl.com/article/51030345/chad-daybell-sentenced-to-death-for-the-murders-of-tammy-daybell-jj-vallow-and-tylee-ryan", "Opened. Sentenced to death on 1 June 2024 for three murders."),
    ("Court filing, case FC2019-092936 (19 page images from the producer)", "ep1_src/images/div_p01.jpg to div_p19.jpg", "Read by OCR (every page searched for the quoted words). Stamp on page 1: 2/15/2019."),
    ("Wikimedia licence list (_CREDITS.csv)", "ep1_src/images/_CREDITS.csv", "Opened. Chris J CC BY-SA 2.0; Tony Webster CC BY 2.0."),
    ("Producer README for the image and footage pack", "ep1_src/images/_README.txt", "Opened. States the bodycam clips are 'rough-cut use only, not cleared for broadcast'."),
    ("Law&Crime article on the bodycam", "https://lawandcrime.com/crazy/body-cam-video-shows-lori-vallows-husband-telling-cops-she-threatened-to-kill-him-he-died-months-later/", "Not opened (HTTP 403)."),
    ("Court TV, 'Charles Vallow's warnings to police'", "https://www.courttv.com/news/charles-vallows-warnings-to-police-and-history-with-lori-daybell/", "Not opened (HTTP 403); read only as a search summary, so its quote is UNVERIFIED."),
]

NOT_CHECKED = [
    "Voiceover: supplied by the producer; not reviewed for rights or for an AI or cloned voice.",
    "Background music: supplied by the producer; licence not on file.",
    "Sound effects: bass hits come from the HyperFrames bundled library; other SFX were synthesised by us. Licence of the bundled files not checked.",
    "Source codes: no footage/sources.csv exists for this show, so no source codes are logged.",
    "OSIRA_CONTEXT_HANDOFF.md and the source registry were not available, so every source was researched from scratch and nothing was reused.",
    "How each file was obtained: the producer supplied the files; the capture method is not recorded for any of them.",
]
